# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirmWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 1000)
        MainWindow.setMinimumSize(QtCore.QSize(800, 1000))
        MainWindow.setMaximumSize(QtCore.QSize(800, 1000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageView = QtWidgets.QGraphicsView(self.centralwidget)
        self.imageView.setMinimumSize(QtCore.QSize(8, 100))
        self.imageView.setMaximumSize(QtCore.QSize(780, 875))
        self.imageView.setObjectName("imageView")
        self.verticalLayout.addWidget(self.imageView)
        self.navigationLayout = QtWidgets.QHBoxLayout()
        self.navigationLayout.setObjectName("navigationLayout")
        self.prevPageButton = QtWidgets.QPushButton(self.centralwidget)
        self.prevPageButton.setObjectName("prevPageButton")
        self.navigationLayout.addWidget(self.prevPageButton)
        self.nextPageButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextPageButton.setObjectName("nextPageButton")
        self.navigationLayout.addWidget(self.nextPageButton)
        self.verticalLayout.addLayout(self.navigationLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.currentTitleLabel0 = QtWidgets.QLabel(self.centralwidget)
        self.currentTitleLabel0.setEnabled(True)
        self.currentTitleLabel0.setMinimumSize(QtCore.QSize(0, 0))
        self.currentTitleLabel0.setMaximumSize(QtCore.QSize(60, 16777215))
        self.currentTitleLabel0.setObjectName("currentTitleLabel0")
        self.horizontalLayout.addWidget(self.currentTitleLabel0)
        self.currentTitleLabel = QtWidgets.QLineEdit(self.centralwidget)
        self.currentTitleLabel.setMinimumSize(QtCore.QSize(500, 0))
        self.currentTitleLabel.setMaximumSize(QtCore.QSize(600, 16777215))
        self.currentTitleLabel.setObjectName("currentTitleLabel")
        self.horizontalLayout.addWidget(self.currentTitleLabel)
        self.pageConfirmLayout = QtWidgets.QHBoxLayout()
        self.pageConfirmLayout.setObjectName("pageConfirmLayout")
        self.pageConfirmLabel = QtWidgets.QLabel(self.centralwidget)
        self.pageConfirmLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pageConfirmLabel.setObjectName("pageConfirmLabel")
        self.pageConfirmLayout.addWidget(self.pageConfirmLabel)
        self.pageConfirmLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pageConfirmLineEdit.setMaximumSize(QtCore.QSize(75, 16777215))
        self.pageConfirmLineEdit.setObjectName("pageConfirmLineEdit")
        self.pageConfirmLayout.addWidget(self.pageConfirmLineEdit)
        self.horizontalLayout.addLayout(self.pageConfirmLayout)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.progressLayout = QtWidgets.QHBoxLayout()
        self.progressLayout.setObjectName("progressLayout")
        self.progressLabel = QtWidgets.QLabel(self.centralwidget)
        self.progressLabel.setObjectName("progressLabel")
        self.progressLayout.addWidget(self.progressLabel)
        self.progressButtonsLayout = QtWidgets.QHBoxLayout()
        self.progressButtonsLayout.setObjectName("progressButtonsLayout")
        self.prevItemButton = QtWidgets.QPushButton(self.centralwidget)
        self.prevItemButton.setObjectName("prevItemButton")
        self.progressButtonsLayout.addWidget(self.prevItemButton)
        self.nextItemButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextItemButton.setObjectName("nextItemButton")
        self.progressButtonsLayout.addWidget(self.nextItemButton)
        self.progressLayout.addLayout(self.progressButtonsLayout)
        self.verticalLayout.addLayout(self.progressLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.prevPageButton.setText(_translate("MainWindow", "上一页"))
        self.nextPageButton.setText(_translate("MainWindow", "下一页"))
        self.currentTitleLabel0.setText(_translate("MainWindow", "当前标题："))
        self.pageConfirmLabel.setText(_translate("MainWindow", "页码确认："))
        self.progressLabel.setText(_translate("MainWindow", "处理进度："))
        self.prevItemButton.setText(_translate("MainWindow", "上一条"))
        self.nextItemButton.setText(_translate("MainWindow", "下一条"))
