# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pdfCard.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(623, 184)
        Form.setMinimumSize(QtCore.QSize(0, 184))
        Form.setMaximumSize(QtCore.QSize(16777215, 184))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_2.setSpacing(16)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setMinimumSize(QtCore.QSize(120, 160))
        self.graphicsView.setMaximumSize(QtCore.QSize(120, 160))
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_2.addWidget(self.graphicsView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pdfNameLabel = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pdfNameLabel.setFont(font)
        self.pdfNameLabel.setObjectName("pdfNameLabel")
        self.verticalLayout.addWidget(self.pdfNameLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pageSettingsLayout = QtWidgets.QHBoxLayout()
        self.pageSettingsLayout.setSpacing(12)
        self.pageSettingsLayout.setObjectName("pageSettingsLayout")
        self.tocStartLabel = QtWidgets.QLabel(Form)
        self.tocStartLabel.setObjectName("tocStartLabel")
        self.pageSettingsLayout.addWidget(self.tocStartLabel)
        self.tocStartSpinBox = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setKerning(True)
        self.tocStartSpinBox.setFont(font)
        self.tocStartSpinBox.setMinimum(1)
        self.tocStartSpinBox.setObjectName("tocStartSpinBox")
        self.pageSettingsLayout.addWidget(self.tocStartSpinBox)
        self.tocEndLabel = QtWidgets.QLabel(Form)
        self.tocEndLabel.setObjectName("tocEndLabel")
        self.pageSettingsLayout.addWidget(self.tocEndLabel)
        self.tocEndSpinBox = QtWidgets.QSpinBox(Form)
        self.tocEndSpinBox.setMinimum(1)
        self.tocEndSpinBox.setObjectName("tocEndSpinBox")
        self.pageSettingsLayout.addWidget(self.tocEndSpinBox)
        self.contentStartLabel = QtWidgets.QLabel(Form)
        self.contentStartLabel.setObjectName("contentStartLabel")
        self.pageSettingsLayout.addWidget(self.contentStartLabel)
        self.contentStartSpinBox = QtWidgets.QSpinBox(Form)
        self.contentStartSpinBox.setMinimum(1)
        self.contentStartSpinBox.setObjectName("contentStartSpinBox")
        self.pageSettingsLayout.addWidget(self.contentStartSpinBox)
        self.verticalLayout.addLayout(self.pageSettingsLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.deletePDF = QtWidgets.QPushButton(Form)
        self.deletePDF.setObjectName("deletePDF")
        self.verticalLayout.addWidget(self.deletePDF)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setStyleSheet(_translate("Form", "\n"
"    QWidget#Form {\n"
"        background-color: white;\n"
"        border: 1px solid #E5E7EB;\n"
"        border-radius: 8px;\n"
"    }\n"
"   "))
        self.graphicsView.setStyleSheet(_translate("Form", "\n"
"       QGraphicsView {\n"
"           background-color: #F3F4F6;\n"
"           border: 1px solid #E5E7EB;\n"
"           border-radius: 4px;\n"
"       }\n"
"      "))
        self.pdfNameLabel.setStyleSheet(_translate("Form", "\n"
"         QLabel {\n"
"             font-size: 14px;\n"
"             font-weight: bold;\n"
"             color: #374151;\n"
"             background-color: #F9FAFB;\n"
"             padding: 4px 8px;\n"
"             border-radius: 4px;\n"
"         }\n"
"        "))
        self.pdfNameLabel.setText(_translate("Form", "PDF 名称"))
        self.tocStartLabel.setStyleSheet(_translate("Form", "\n"
"           QLabel {\n"
"               color: #374151;\n"
"               font-size: 13px;\n"
"           }\n"
"          "))
        self.tocStartLabel.setText(_translate("Form", "目录起始页"))
        self.tocStartSpinBox.setStyleSheet(_translate("Form", "\n"
"           QSpinBox {\n"
"               padding: 4px;\n"
"               border: 1px solid #D1D5DB;\n"
"               border-radius: 4px;\n"
"               background-color: white;\n"
"           }\n"
"           QSpinBox:focus {\n"
"               border-color: #3B82F6;\n"
"           }\n"
"          "))
        self.tocEndLabel.setStyleSheet(_translate("Form", "\n"
"           QLabel {\n"
"               color: #374151;\n"
"               font-size: 13px;\n"
"           }\n"
"          "))
        self.tocEndLabel.setText(_translate("Form", "目录结束页"))
        self.tocEndSpinBox.setStyleSheet(_translate("Form", "\n"
"           QSpinBox {\n"
"               padding: 4px;\n"
"               border: 1px solid #D1D5DB;\n"
"               border-radius: 4px;\n"
"               background-color: white;\n"
"           }\n"
"           QSpinBox:focus {\n"
"               border-color: #3B82F6;\n"
"           }\n"
"          "))
        self.contentStartLabel.setStyleSheet(_translate("Form", "\n"
"           QLabel {\n"
"               color: #374151;\n"
"               font-size: 13px;\n"
"           }\n"
"          "))
        self.contentStartLabel.setText(_translate("Form", "正文起始页"))
        self.contentStartSpinBox.setStyleSheet(_translate("Form", "\n"
"           QSpinBox {\n"
"               padding: 4px;\n"
"               border: 1px solid #D1D5DB;\n"
"               border-radius: 4px;\n"
"               background-color: white;\n"
"           }\n"
"           QSpinBox:focus {\n"
"               border-color: #3B82F6;\n"
"           }\n"
"          "))
        self.deletePDF.setText(_translate("Form", "删除 PDF"))
