name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        choco install poppler
        echo "C:\Program Files\poppler\Library\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build executable
      run: |
        mkdir dist/application/data
        pyinstaller --noconfirm --console --name "application" \
        --add-data ".env;." \
        --add-data "mainprogram;mainprogram" \
        --add-data "templates/index.txt;templates" app.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: application
        path: dist/application/